// One-line definitions shown on hover for every metric (data-tip="key").
export const GLOSSARY = {
  total: 'Total excess return over financing at the horizon: bond value + coupons (reinvested at the financing rate) − financed cost.',
  carry: 'The bond ages at its own constant yield (coupon income + pull-to-par), minus the cost of financing the position.',
  roll: 'Price gain from the bond rolling down today\'s unchanged curve to a shorter maturity (vs ageing at its own yield).',
  curve: 'Revaluation from your expected curve versus today\'s unchanged curve at the same date.',
  priced_in: 'What you earn if the forwards are realised: carry + roll-down + the curve move the forwards already imply.',
  priced_move: 'The curve change implied by the forwards (forward curve vs today\'s curve), valued on the position.',
  edge: 'View vs forwards: return from your expected path deviating from the forward curve. Forwards embed term premium, so a gain here can be risk compensation, not only forecasting skill.',
  basis_total: 'Holding-period return: (value at horizon + coupons received, reinvested at the cash rate − price paid) ÷ price paid. No financing.',
  basis_excess: 'Excess over financing: you borrow the price at the repo/cash rate; P&L is what the bond earns beyond that funding cost.',
  target: 'Target return, % per year on gross market value (compounded over the horizon for holding-period returns).',
  inflation: 'Inflation vs priced: TIPS index accretion under your CPI path minus the accretion breakevens price. Zero for nominal bonds.',
  real_rates: 'First-order P&L from changes in real yields (nominal = real + breakeven).',
  breakevens: 'First-order P&L from changes in breakeven inflation (nominal − real yields).',
  passthrough: 'Share of your breakeven change that moves nominal yields. 100%: real yields held (Fisher). 0%: nominal yields as you set them, real yields absorb it.',
  cpi: 'Realised CPI inflation, % a year, that drives TIPS index accretion to the horizon.',
  be_curve: 'Breakeven inflation: nominal minus real (TIPS) zero rates. Includes inflation risk and liquidity premia; read as expectations by convention.',
  view_fraction: 'Share of your view (vs today\'s curve) that must happen for the target; 100% = exactly your view.',
  latest: 'If your view arrives linearly but later, the latest date by which it must be complete for the target to be met at the horizon.',
  room: 'Parallel move away from your own expected curve that the position can absorb before missing the target.',
  convexity: 'Second-order effect of the curve move (½·Σ c·τ²·DF·Δ²) plus a small higher-order residual; sums close the identity exactly.',
  residual: 'Higher-order term left after first-order and convexity; tiny by construction.',
  spread: 'Revaluation from the credit-spread path (credit lines only).',
  other_shape: 'Part of the first-order curve effect not explained by level/slope/curvature (shape outside the 3 factors).',
  bucket: 'Key-rate bucket: each cash flow\'s first-order P&L mapped onto neighbouring key tenors with linear (tent) weights; buckets sum exactly.',
  level: 'Level factor: a (weighted-average) parallel move of the curve, in bp.',
  slope: 'Slope factor, scaled so +1bp = 2s10s steepens 1bp.',
  curvature: 'Curvature factor, scaled so +1bp = 2s5s10s fly (2·5y − 2y − 10y) rises 1bp (belly cheapens).',
  breakeven_parallel: 'Parallel move at the horizon that makes total excess return zero (vs today\'s curve, and vs the forward curve).',
  breakeven_slope: 'Slope-factor move (2s10s bp) at the horizon that makes total excess return zero.',
  cover: 'Time until carry + roll-down accumulated so far offsets an adverse move of the given size applied at that date.',
  sigma: 'One standard deviation of horizon P&L from historical daily key-rate covariance, scaled by √horizon.',
  ratio: 'Expected return per unit of volatility over the horizon (expected P&L ÷ 1σ).',
  dv01: 'Dollar value of a 1bp parallel rise in zero rates (negative = loses when rates rise), per position.',
  krd: 'Key-rate DV01: $ change per +1bp at one key tenor with linear tents to neighbouring tenors.',
  fwd: 'Market-implied curve at date t: the forward curve implied by today\'s zero curve (what is priced in).',
  today: 'Today\'s fitted zero curve (continuously compounded), held unchanged in maturity.',
  yours: 'Your expected curve at date t, built from your nodes / policy path.',
  edge_bp: 'Your expected zero rate minus the market-implied (forward) rate at that tenor and date.',
  vs_today: 'Your expected zero rate minus today\'s zero rate at the same maturity.',
  anchor: 'Between nodes your deviation is interpolated relative to this anchor: the forwards (view stated vs priced) or today\'s curve.',
  pnl_mc: 'Distribution of horizon P&L from simulated key-rate shocks (historical covariance) around your path.',
  p_loss: 'Probability of a negative horizon excess return under the simulated distribution.',
  gross_mv: 'Sum of absolute market values of all lines; bp figures are P&L ÷ gross MV.',
  implied_rate: 'Financing rate equal to today\'s zero rate to the horizon — makes priced-in excess return ≈ 0.',
  mod_dur: 'Curve duration: −(1/P)·dP/dz for a parallel zero-rate shift.',
  tp: 'Change in term premium (vs what the forwards embed) by the horizon, phased in linearly.',
  half_life: 'After the last meeting you set, your deviation from the priced path decays back to the forwards with this half-life.',
  convergence: 'How fast the market converges to your path for meetings not yet held (0 = immediately).',
  fit: 'Model yield minus quoted CMT yield (bp). The curve is smoothed: bills carry idiosyncratic noise.',
  timing: 'Same end-state curve reached at different speeds. Buy-and-hold horizon P&L is identical; the path and exit returns differ.',
  realised: 'Return if you close the trade the moment the view has fully played out, annualised.',
  drawdown: 'Largest peak-to-trough fall in cumulative P&L along the path.',
};
